# Generated by Django 2.2.4 on 2019-08-28 19:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('referenceIdentifier', django.contrib.postgres.fields.jsonb.JSONField()),
                ('scripture', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Confessions')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Headings')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Passages')),
            ],
        ),
    ]
