# Generated by Django 2.2.4 on 2019-08-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citations',
            old_name='confessionId',
            new_name='confession',
        ),
        migrations.RenameField(
            model_name='citations',
            old_name='headingId',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='citations',
            old_name='passageId',
            new_name='passage',
        ),
    ]
