# Generated by Django 2.1.9 on 2019-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='referenceIdentifier',
            field=models.CharField(max_length=1000),
        ),
    ]
