# Generated by Django 2.1.9 on 2019-09-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confessions',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('heading_number', models.IntegerField()),
                ('title', models.TextField()),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Confessions')),
            ],
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('passage_number', models.IntegerField()),
                ('passage', models.TextField()),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Confessions')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Headings')),
            ],
        ),
    ]
