# Generated by Django 2.2.4 on 2019-08-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confessions',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('confessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Confessions')),
            ],
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('passage', models.TextField()),
                ('confessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Confessions')),
                ('headingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Headings')),
            ],
        ),
    ]
