# Generated by Django 2.1.9 on 2019-09-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passages',
            name='heading_number',
            field=models.IntegerField(default=0),
        ),
    ]
