# Generated by Django 2.2.4 on 2019-08-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_auto_20190824_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headings',
            old_name='confessionId',
            new_name='confession',
        ),
        migrations.RenameField(
            model_name='passages',
            old_name='confessionId',
            new_name='confession',
        ),
        migrations.RenameField(
            model_name='passages',
            old_name='headingId',
            new_name='heading',
        ),
    ]
