# Generated by Django 2.2.4 on 2019-08-01 15:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wcf',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('proofs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
